### ISSUE TITLE
[Meta] Improve office world

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino_gz#60]
### Summary

![image](https://github.com/Ekumen-OS/andino_gz/assets/53065142/fe4e1e57-df08-4b9b-b0b6-88303599cdf3)

Improve overall world
 - Add a floor
 - Add textures to the walls
 - Add office assets
 - Add lights

### Suggestions
 - Let's work on blender. 
 - Use current stl as guidelines for the walls
 - Use objects for different parts of the office:
   - Walls:
   - Wooden Floor 
   - Tile Floor
 - Textures
   - Apply pbr textures (at least albedo, normals and roughness)
     - For walls: All white for the moment is ok.
     - Size: Let's keep size of textures <10mb 

### Labor breakdown
Blender
 - [x] Object1: Base world creation with only walls. No textures applied.
 - [x] Object2: Add tile floor to the entire space. No textures applied
 - [x] Object3: Add wooden floor just to the wooden floor area. No textures applied.
 - [ ] Object4: Add basic roof
      Normals of the mesh pointing down would allows us to see it from above in the sim :smile: 
 - [x] Apply textures to walls.
 - [x] Apply textures to tile floor.
 - [x] Apply texture to wooden floor.
 - [x] Export to a office.dae: walls, tile_floor and wooden_floor will be submeshes

Gazebo
 - [x] Create office model and costume the dae files and apply PBR textures
 - [x] Create sdf world and use the office model.
 - [x] Create a office_populated world that consumes the same office model but add some office assets in the world.
 - [ ] Add correct lightning. There is no need for visual lamp assets for the first iteration of it.

**Comment by francocipollone** [comment]
I am closing this issue and creating a new one for more accurate tasks
