### ISSUE TITLE
AndinoGz release via ROS

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino_gz#68]
### Summary

Let's release andino_gz!

### Docs
https://docs.ros.org/en/humble/How-To-Guides/Releasing/Releasing-a-Package.html
http://wiki.ros.org/buildfarm/Pull%20request%20testing
https://docs.ros.org/en/eloquent/Tutorials/Releasing-a-ROS-2-package-with-bloom.html
https://github.com/Ekumen-OS/andino/issues/154

### PreTasks
 - [x] Verify naming conventions/licensing / etc

### Tasks

- [x] Add andino_gz entry point to humble index
     - https://github.com/ros/rosdistro/pull/42167 
- [x] Add andino_gz to andino [team](https://docs.ros.org/en/rolling/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository) and create release repo at https://github.com/ros2-gbp/ros2-gbp-github-org
       -  https://github.com/ros2-gbp/ros2-gbp-github-org/issues/572
- [x] Link Jenkins build with Git Hub. http://wiki.ros.org/buildfarm/Pull%20request%20testing
- [x] Bloom release : https://github.com/ros/rosdistro/pull/42456

**Comment by francocipollone** [comment]
Testing locally with pre-releases binaries: https://docs.ros.org/en/humble/Installation/Testing.html

Tested using rocker:

 - ```rocker --nvidia --x11 osrf/ros:humble-desktop-full /bin/bash```
 - Point to ros2-testing repo
 - apt update && apt install ros-humble-andino-gz
 -  ```ros2 launch andino_gz andino_gz.launch.py nav2:=True```
 
 
 It works good: 
![image](https://github.com/user-attachments/assets/98d1ebba-cce0-457e-9410-5568b9d329f2)
